### ISSUE TITLE
Support setting HTTP headers for WebSocket connection

### ISSUE THREAD

**Issue by wolfman42** [nats-io/nats.net#305]
### Proposed change

Support setting of (additional) HTTP headers for WebSocket connection. This could be a new part of NatsOpts class. Useful for providing an Authorization header. Perhaps along the following lines:

```csharp
        var opts = new NatsOpts {
            Url = $"wss://localhost:8181"
        };
        opts.SetWebSocketHeader("authorization", $"Bearer {accessToken}");
        await using var nats = new NatsConnection(opts);
        await nats.PingAsync();
```
OnConnectingAsync callback should allow updating the headers, so that an authorization token could be refreshed.

### Use case

JWT based authorization outside of NATS server.

### Contribution

yes, interested.

**Comment by caleblloyd** [comment]
I don't think that WebSockets support HTTP Headers.  I've been frustrated by this before :smile: 

https://stackoverflow.com/a/4361358

SignalR Core [uses a query string parameter ](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0#bearer-token-authentication) to transmit bearer tokens over websockets

**Comment by wolfman42** [comment]
> I don't think that WebSockets support HTTP Headers. I've been frustrated by this before 😄
> 
> https://stackoverflow.com/a/4361358
> 
> SignalR Core [uses a query string parameter ](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0#bearer-token-authentication) to transmit bearer tokens over websockets

WebSockets in C# (and most other languages / frameworks) do support HTTP headers. The only situation when it's not supported (AFAIK) is when you try to connect a WebSocket from a browser application.

**Comment by caleblloyd** [comment]
Good to know.  Maybe we could pass a callback:

```
Func<Uri, ValueTask<ClientWebSocketOptions>> ConfigureWebSocketOpts
```

Where the `Uri` argument is the URI of the NATS Server we are attempting to connect to

**Comment by adamreed90** [comment]
👍 I could see this being extremely useful with Blazor WebAssembly, specifically with being able to securely emit events from the frontend without the need for SignalR

**Comment by caleblloyd** [comment]
I think that Blazor WebAssembly running in the browser will use the Browser's websocket implementation, which doesn't support headers.

**Comment by srs-adamr** [comment]
> I think that Blazor WebAssembly running in the browser will use the Browser's websocket implementation, which doesn't support headers.

Correct, I was speaking in support of the ability to authenticate with a token or some other form of authentication via WebSockets being supported, would allow developers an alternative to SignalR for frontend messaging.
