### ISSUE TITLE
No reply received

### ISSUE THREAD

**Issue by copycd** [nats-io/nats.net#499]
### Observed behavior

after A "No reply received" error occurs, and followed by a "No responders" error.
it's success if request count is 100 ~ 200.
but it's failed if over about 500 ~ 1000
the both code is running on same machine.

my log of error is.
2024-05-19 16:29:44.736 +09:00 [ERR] No reply received
2024-05-19 16:29:44.737 +09:00 [ERR] NATS.Client.Core.NatsNoReplyException: No reply received
   at NATS.Client.Core.NatsConnection.RequestAsync[TRequest,TReply](String subject, TRequest data, NatsHeaders headers, INatsSerialize`1 requestSerializer, INatsDeserialize`1 replySerializer, NatsPubOpts requestOpts, NatsSubOpts replyOpts, CancellationToken cancellationToken)
   at NATS.Client.Core.NatsConnection.RequestAsync[TRequest,TReply](String subject, TRequest data, NatsHeaders headers, INatsSerialize`1 requestSerializer, INatsDeserialize`1 replySerializer, NatsPubOpts requestOpts, NatsSubOpts replyOpts, CancellationToken cancellationToken)
2024-05-19 16:29:44.738 +09:00 [ERR] No responders
2024-05-19 16:29:44.738 +09:00 [ERR] NATS.Client.Core.NatsNoRespondersException: No responders
   at NATS.Client.Core.NatsSubBase.DisposeAsync()
   at NATS.Client.Core.NatsConnection.RequestAsync[TRequest,TReply](String subject, TRequest data, NatsHeaders headers, INatsSerialize`1 requestSerializer, INatsDeserialize`1 replySerializer, NatsPubOpts requestOpts, NatsSubOpts replyOpts, CancellationToken cancellationToken)

my subscribe code below:

            NatsSubOpts subOpts = new NatsSubOpts() { ChannelOpts  = new NatsSubChannelOpts() { Capacity = 5000 } };
            await using var sub = await natsConn.SubscribeCoreAsync<byte[]>($"{subJect}", queueGroup:groupName, opts:subOpts);
            var reader = sub.Msgs;
              while (await reader.WaitToReadAsync())
              {
                  while (reader.TryRead(out NatsMsg<byte[]> msg))
                  {
                      var t = Task.Run(() =>
                      {
                          Interlocked.Increment(ref _listenCount);

                          if (msg.ReplyTo != null)
                          {
                              string strMsg = $"Tester{_name}:{subJect} received : {_listenCount}";
                              msg.ReplyAsync(strMsg);
                          }
                      });
                  }
              }

my request code below:

               var replyOpts = new NatsSubOpts { Timeout = TimeSpan.FromSeconds(5) };
                for (int i = 0; i < requestCount; i++)
                {
                    try
                    {
                        var reply = await natsConn.RequestAsync<byte[], string>(subject, sendBytes, replyOpts: replyOpts);
                    }
                    catch (Exception e)
                    {
                        _logger.err(e.Message);
                        _logger.err($"{e}");
                    }
                }

### Expected behavior

not error.

### Server and client version

server Version:  2.10.14  (windows)
client NATS.Net ( 2.2.1 )

**Comment by mtmk** [comment]
Thanks for the report. Does changing the message dropping behaviour help?
```csharp
await using var nats = new NatsConnection(new NatsOpts
{
    SubPendingChannelFullMode = BoundedChannelFullMode.Wait,
});
```

**Comment by copycd** [comment]
thanks for your answer.
Even so done, the same error occurs.
By the way, I found another case.
Keep the subscriber the same code that upper,
I put publisher as java code, and even if I do over 10000 cases, that receive them correctly.

**Comment by darkwatchuk** [comment]
I can repro the issue with the code below.  This is a slightly altered version of the original posting.  I've added multiple sender tasks, and have also included the await and async as @mtmk  suggested.  However the async/await seems to make little difference.

Interestingly, running this code inside Visual Studio doesn't seem to exhibit the issue.  Running outside of VS directly from powershell I get the following.....

<pre>
creating sender task 12
creating sender task 13
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
warn: NATS.Client.Core.Internal.SubscriptionManager[1002]
      Subscription GCd but was never disposed subject/1
Send 75 : No responders
Send 76 : No responders
Send 76 : No responders
Send 76 : No responders
</pre>


<pre>
using Microsoft.Extensions.Logging;
using NATS.Client.Core;
using NATS.Client.JetStream;

var config = new NatsOpts
{
    Url = "nats://127.0.0.1",
    LoggerFactory = LoggerFactory.Create(builder => builder.AddConsole()),
};

var natsConn= new NatsConnection(config);

string subject = "subject";
string _name = "bob";

_ = Task.Run(Receive);

await Task.Delay(2000);

List<Task> tasks = new List<Task>();
for (int i = 0; i < 14; i++)
{

    Console.WriteLine($"creating sender task {i}");
    tasks.Add(Send(16000));
}

Task.WaitAll(Task.WhenAll(tasks));

Console.WriteLine("done");

async Task Send(int requestCount)
{
    byte[] sendBytes = new byte[123024];

    var replyOpts = new NatsSubOpts { Timeout = TimeSpan.FromSeconds(5) };
    for (int i = 0; i < requestCount; i++)
    {
        try
        {
            var reply = await natsConn.RequestAsync<byte[], string>(subject, sendBytes, replyOpts: replyOpts);
            //Console.WriteLine(reply);
        }
        catch (Exception e)
        {
            Console.WriteLine($"Send {i} : {e.Message}");            
        }
    }

}

async Task Receive()
{
    long _listenCount = 0;
    string groupName = "group";
    

    NatsSubOpts subOpts = new NatsSubOpts() { ChannelOpts = new NatsSubChannelOpts() { Capacity = 5000 } };
    await using var sub = await natsConn.SubscribeCoreAsync<byte[]>($"{subject}", queueGroup: groupName, opts: subOpts);
    var reader = sub.Msgs;
    while (await reader.WaitToReadAsync())
    {
        while (reader.TryRead(out NatsMsg<byte[]> msg))
        {
            var t = Task.Run( async () =>                                                           // <<<<<<---- added async
            {
                Interlocked.Increment(ref _listenCount);
                try
                {
                    if (msg.ReplyTo != null)
                    {
                        string strMsg = $"Tester{_name}:{subject} received : {_listenCount}";
                        await msg.ReplyAsync(strMsg);                                                     //  <<<<<<<<---------- added await
                    }
                }
                catch (Exception e)
                {                    
                    Console.WriteLine($"Receive : {e.Message}");
                }
                
            });
        }
    }
}
</pre>

**Comment by mtmk** [comment]
thanks @darkwatchuk I can reproduce that too. I think problem might be `Subscription GCd but was never disposed subject/1` which means either inbox or responder subscription is quitting for some reason and is causing the no responders error (which means server could not find a subscription for a given publish message). will try to dig deeper.

**Comment by mtmk** [comment]
ok I think not holding on to the subscription might be the issue. We have few people tripping up with this now and again. We keep a weak reference to the subscription object in cases where application code might not properly dispose the subscription, we can then unsubscribe from the server to keep things nice and tidy. but in some cases it is unsubscribing unexpectedly because GC is kicking in because of the weak reference. You can either hold on to the subscription yourself or use the SubscribeAsync enumerable where we do that for you internally. I was able to run the code to completion with changes below. thanks again for the repro @darkwatchuk 💯 

```csharp
using System.Threading.Channels;
using Microsoft.Extensions.Logging;
using NATS.Client.Core;

var config = new NatsOpts
{
    Url = "nats://127.0.0.1",
    LoggerFactory = LoggerFactory.Create(builder => builder.AddConsole()),
};

var natsConn= new NatsConnection(config);

string subject = "subject";
string _name = "bob";

// string groupName = "group";
// var subOpts = new NatsSubOpts() { ChannelOpts = new NatsSubChannelOpts() { Capacity = 5000 } };
// await using var sub = await natsConn.SubscribeCoreAsync<byte[]>($"{subject}", queueGroup: groupName, opts: subOpts);
// ChannelReader<NatsMsg<byte[]>> reader1 = sub.Msgs;
//
// _ = Task.Run(async () => await Receive(reader1));

_ = Task.Run(Receive2);

await Task.Delay(2000);

List<Task> tasks = new List<Task>();
for (int i = 0; i < 14; i++)
{

    Console.WriteLine($"creating sender task {i}");
    tasks.Add(Send(16000));
}

Task.WaitAll(Task.WhenAll(tasks));

Console.WriteLine("done");

async Task Send(int requestCount)
{
    byte[] sendBytes = new byte[123024];

    var replyOpts = new NatsSubOpts { Timeout = TimeSpan.FromSeconds(5) };
    for (int i = 0; i < requestCount; i++)
    {
        try
        {
            var reply = await natsConn.RequestAsync<byte[], string>(subject, sendBytes, replyOpts: replyOpts);
            //Console.WriteLine(reply);
        }
        catch (Exception e)
        {
            //Console.WriteLine($"Send {i} : {e.Message}");
        }
    }

}

async Task Receive(ChannelReader<NatsMsg<byte[]>> reader)
{
    long _listenCount = 0;


    while (await reader.WaitToReadAsync())
    {
        while (reader.TryRead(out NatsMsg<byte[]> msg))
        {
            var t = Task.Run( async () =>                                                           // <<<<<<---- added async
            {
                Interlocked.Increment(ref _listenCount);
                try
                {
                    if (msg.ReplyTo != null)
                    {
                        string strMsg = $"Tester{_name}:{subject} received : {_listenCount}";
                        await msg.ReplyAsync(strMsg);                                                     //  <<<<<<<<---------- added await
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Receive : {e.Message}");
                }

            });
        }
    }
}


async Task Receive2()
{
    long _listenCount = 0;

    string groupName = "group";

    NatsSubOpts subOpts = new NatsSubOpts() { ChannelOpts = new NatsSubChannelOpts() { Capacity = 5000 } };


    await foreach (var msg in natsConn.SubscribeAsync<byte[]>(subject, groupName, opts: subOpts))
    {
        var t = Task.Run( async () =>                                                           // <<<<<<---- added async
            {
                Interlocked.Increment(ref _listenCount);
                try
                {
                    if (msg.ReplyTo != null)
                    {
                        string strMsg = $"Tester{_name}:{subject} received : {_listenCount}";
                        await msg.ReplyAsync(strMsg);                                                     //  <<<<<<<<---------- added await
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Receive : {e.Message}");
                }

            });
    }
}
```

**Comment by darkwatchuk** [comment]
TBH - wasn't aware you could access the ChannelReader in the first place.  Is it not a bit dangerous to expose such a thing?  @copycd used a common pattern to read the channel and of course the weak reference system is behind the scenes - who would know!?!?  What's the point in exposing the ChannelReader?

**Comment by mtmk** [comment]
> TBH - wasn't aware you could access the ChannelReader in the first place. Is it not a bit dangerous to expose such a thing? @copycd used a common pattern to read the channel and of course the weak reference system is behind the scenes - who would know!?!? What's the point in exposing the ChannelReader?

in general application code doesn't need to know about the channels like in the case of using `SubscribeAsync` that returns an async enumerable for `await foreach` (like most other JetStream APIs too) where we take care of the object life cycles internally. We suggest using `SubscribeAsync` for that reason. But if someone wants to use and fine tune a channel we try to provide some knobs for that too maybe for slightly more advanced scenarios.

**Comment by mtmk** [comment]
@Neon4eg do you have other consumer on the same connection?

**Comment by Neon4eg** [comment]
@mtmk I have 2 handlers that are executed one after another, do pretty similar actions (read and write entries to KV store) and all of them use the same connection as NATS connection pool size = 1 by default.
1st hadler works fine, and 2nd one gets NatsNoReplyException for some of the entries, not for all.
I turned off other handler and exception was not thrown.  
Increasing NATS connection pool by 10 does not solve the problem
