### ISSUE TITLE
Modified Timestamp is missing from ObjectStore.GetInfoAsync

### ISSUE THREAD

**Issue by darkwatchuk** [nats-io/nats.net#566]
### Observed behavior

The MTime field on calling GetInfoAsync is coming back as 0, I think it might actually be coming back from the server as 0?

### Expected behavior

MTime should match the MTime for the same object that comes back as part of the ListAsync call

### Server and client version

Server 2.10.17
.NET client 2.3.2

### Host environment

tested locally on windows, unix, and nats.demo.io

### Steps to reproduce

This is a test against the selfies bucket on demo.nats.io
```

  [Fact]
  public async Task TestModifiedTimeStamps()
  {
      var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
      var cancellationToken = cts.Token;

      await using var nats = new NatsConnection(new NatsOpts {
           Url = "nats://demo.nats.io",
      });

      var js = new NatsJSContext(nats);
      var ob = new NatsObjContext(js);

      var objStore = await ob.GetObjectStoreAsync("selfies", cancellationToken);


      const string FILE_NAME = "selfie.png";
      DateTimeOffset? dtFromList = null;
      await foreach (var entry in objStore.ListAsync(cancellationToken: cancellationToken))
      {
          if (entry.Name == FILE_NAME)
          {
              dtFromList = entry.MTime;
              break;
          }
      }

      var f = await objStore.GetInfoAsync(FILE_NAME);
      DateTimeOffset? dtFromInfo = f.MTime;

      Assert.False(dtFromInfo == DateTimeOffset.MinValue, "GetInfo Timestamp is Zero");
      Assert.True(dtFromInfo == dtFromList, "Modified timestamps should match");
  }
```

**Comment by mtmk** [comment]
thanks @darkwatchuk (also thanks for the test, very helpful) server is sending the data. looks like a bug here:

https://github.com/nats-io/nats.net.v2/blob/a7c88e137a429dac85c4e284957a33ff87ab4025/src/NATS.Client.ObjectStore/NatsObjStore.cs#L639-L640

can't remember why I did that except probably (wrongly?) copied from another client implementation. we should probably remove that overwriting mtime line (which passes the test).

fwiw timestamp comes back 'correctly' but because they're not deserialized with the same precision equality doesn't work.

**Comment by darkwatchuk** [comment]
> thanks @darkwatchuk (also thanks for the test, very helpful) server is sending the data. looks like a bug here:
> 
> https://github.com/nats-io/nats.net.v2/blob/a7c88e137a429dac85c4e284957a33ff87ab4025/src/NATS.Client.ObjectStore/NatsObjStore.cs#L639-L640
> 
> can't remember why I did that except probably (wrongly?) copied from another client implementation. we should probably remove that overwriting mtime line (which passes the test).
> 
> fwiw timestamp comes back 'correctly' but because they're not deserialized with the same precision equality doesn't work.

Sorry, been away, was rushed when I reported this, but will look at this in more detail today.  On a quick initial view, it's not those two lines you reported. In fact those lines are required to set the data on the ListAsync.

**Comment by darkwatchuk** [comment]
Raw message coming back was this...

{"name":"selfie.png","options":{"max_chunk_size":131072},"bucket":"selfies","nuid":"mCbWsdT6fZvXZLlvBm8CqH","size":679137,"mtime":"0001-01-01T00:00:00Z","chunks":6,"digest":"SHA-256=i4FTuqa9eqT0K3kD1Ahi60cgPFAyWPUsLJFcca25Nzc="}`

....however the time can be pulled from Message.Time instead (same as KV store) - as you said though, precision is slightly different, just nanoseconds!

```

            var base64String = Convert.FromBase64String(response.Message.Data);
            var data = NatsObjJsonSerializer<ObjectMetadata>.Default.Deserialize(new ReadOnlySequence<byte>(base64String)) ?? throw new NatsObjException("Can't deserialize object metadata");

            if (!DateTimeOffset.TryParse(response.Message.Time, out var created))
                throw new NatsObjException("Can't parse timestamp message value");
            data.MTime = created;

```

**Comment by mtmk** [comment]
fwiw I think meta comes from the reply-to field in the protocol message and the other is whatever we sent before. So meta might be set by the server.

![image](https://github.com/user-attachments/assets/68fffff4-d66e-4ed4-b2c4-7ce9e5a3d819)

**Comment by mtmk** [comment]
> Raw message coming back was this...
> 
> {"name":"selfie.png","options":{"max_chunk_size":131072},"bucket":"selfies","nuid":"mCbWsdT6fZvXZLlvBm8CqH","size":679137,"mtime":"0001-01-01T00:00:00Z","chunks":6,"digest":"SHA-256=i4FTuqa9eqT0K3kD1Ahi60cgPFAyWPUsLJFcca25Nzc="}`

in which case are we getting `"mtime":"0001-01-01T00:00:00Z"`? in the test I believe it does come back with a value.

**Comment by darkwatchuk** [comment]
> > Raw message coming back was this...
> > {"name":"selfie.png","options":{"max_chunk_size":131072},"bucket":"selfies","nuid":"mCbWsdT6fZvXZLlvBm8CqH","size":679137,"mtime":"0001-01-01T00:00:00Z","chunks":6,"digest":"SHA-256=i4FTuqa9eqT0K3kD1Ahi60cgPFAyWPUsLJFcca25Nzc="}`
> 
> in which case are we getting `"mtime":"0001-01-01T00:00:00Z"`? in the test I believe it does come back with a value.

But the wrong value? - Confused - sorry...

**Comment by mtmk** [comment]
no worries, i'm probably missing something. will look at it more closely in a bit
