### ISSUE TITLE
Inability to create Jetstream consumer in nats-server version 2.8 and below

### ISSUE THREAD

**Issue by Ivandemidov00** [nats-io/nats.net#606]
### Observed behavior

When calling the api while connecting to the nats server with version 2.8
```
 await _context.CreateOrUpdateConsumerAsync(
            _stream,
            config,
            cancellationToken: _cancellationToken);
```

I get an error 
`NatsJSApiNoResponseException: No API response received from the server`

This is due to the fact that the `$JS.API.CONSUMER.CREATE` api is used to create a consumer, regardless from the nats-server version
For create a consumer in nats-server 2.8, we must use the api `$JS.API.CONSUMER.DURABLE.CREATE`

I looked at the code for the necessary functionality todo is already there
`// TODO: Adjust API subject according to server version and filter subject`

### Expected behavior

Ability to create consumers regardless of nat-server version

### Server and client version

Nats-Server: 2.8.*
NATS.NET 2.3.3

**Comment by Ivandemidov00** [comment]
If no has any objections, I can solve this problem

**Comment by Jarema** [comment]
Hey!
Thanks for opening the issue.

Unfortunately, there is no reliable way to determine server version of the JetStream meta leader which is responsible for handling the request.

Server info of server to which client is connected should not be used: there is no gurantee that this is a JS meta leader, and in case of leafnodes, chance for having different version is high.


Additionaly, nats 2.8 is a really old version and is not supported anymore. Please consider upgrading.

We are planning to introduce some improved safeguard and checks around versions in nats 2.11 or 2.12

**Comment by Ivandemidov00** [comment]
Yes, I forgot about the possibility of Leaf Nodes, as well the possibility of changing the meta leader. Thanks.
I think can close this issue
