### ISSUE TITLE
MaxMsg=1 not respected. second message ALWAYS gets redelivered as if its ackwait started before yielded

### ISSUE THREAD

**Issue by mattbdc** [nats-io/nats.net#608]
MaxMsg=1 not respected. second message ALWAYS gets redelivered when ack'ed within time, it is  as if its ackwait started before yielded (as if MaxMsg 1 wasn't originally respected and this is was in the buffer before the loop back to foreach). Theory only. Reproducible consistently.  I get the point that one should handle  redeliveries via idempotency onwards or some KV lookup to check, due to anything from network partitions, server restarts, client crashes, internal buffers being too strained, and so on, but this is consistently reproducible locally. 

### Observed behavior (local setup VM and client app next to each other, no network chat)

```using NATS.Client.Core;
using NATS.Client.JetStream;

Console.WriteLine("Start");

var c = new NatsConnection(new NatsOpts()
{
    Url = "nats://127.0.0.1:4222"
});

var s = new NatsJSContext(c);
var consumer = await s.GetConsumerAsync("email-queue", "email-queue-consumer");

await foreach(var i in consumer.ConsumeAsync<string>(opts: new NatsJSConsumeOpts() {
                  MaxMsgs = 1
})) {
    Console.WriteLine("TS" + DateTime.UtcNow + "   -> " + i.Data);
    await Task.Delay(32500); // ack wait configured to 36second on consumer config
    await i.AckAsync();
}
Console.WriteLine("Done");

```

consumer
```
Configuration:

                    Name: email-queue-consumer
               Pull Mode: true
          Deliver Policy: All
              Ack Policy: Explicit
                Ack Wait: 36.00s
           Replay Policy: Instant
      Maximum Deliveries: 2
         Max Ack Pending: 1,000
       Max Waiting Pulls: 512

State:

  Last Delivered Message: Consumer sequence: 20 Stream sequence: 14 Last delivery: 1m49s ago
    Acknowledgment Floor: Consumer sequence: 20 Stream sequence: 14 Last Ack: 40.49s ago
        Outstanding Acks: 0 out of maximum 1,000
    Redelivered Messages: 0
    Unprocessed Messages: 0
           Waiting Pulls: 1 of maximum 512
```

```
➜  ~ nats stream info email-queue
Information for Stream email-queue created 2024-07-18 12:13:40

              Subjects: email.queue
              Replicas: 1
               Storage: File

Options:

             Retention: WorkQueue
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 2m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: 1d0h0m0s
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

State:

              Messages: 0
                 Bytes: 0 B
        First Sequence: 17
         Last Sequence: 16 @ 2024-08-22 12:09:39 UTC
      Active Consumers: 1

```

Once setup run this:

```
nats publish email.queue 'ahhh1'
nats publish email.queue 'ahhh2'
```
### Expected behavior

shouldnt see second message 2 times. as acked within 32.5 seconds when ackwait is 36s

### Server and client version

v2.10.17 and    "NATS.Net" Version="2.3.3". All local Fedora 40.  Dotnet 8. Plenty of resources.  No docker.

### Host environment

linux, localhost, all same machine

### Steps to reproduce

setup stream and consumer via cli
build and start dotnet simple app
nats publish email.queue 'ahhh1'
nats publish email.queue 'ahhh2'

**Comment by mtmk** [comment]
maybe related to #508

**Comment by mtmk** [comment]
thanks for the detailed report @mattbdc I think you're right it's a bug. I was working on a fix in #508  are you able to check that branch if it fixes this issue?

**Comment by mtmk** [comment]
> it's strange no one else seems to have noticed this

There was a discussion on slack: https://natsio.slack.com/archives/C1V81FKU6/p1717497381540349

unfortunately slack clears after certain amount of time. here is a copy of the initial message:
> What role is MaxMsgs (defined in NatsJsConsumeOpts) supposed to play in ConsumeAsync? We were expecting it to set a ceiling to how many messages the client may fetch from the consumer in a pull request.
That is, the client would keep an internal buffer of - at most -  MaxMsgs pre-fetched msgs, from which it would yield the messages to the caller code. And once the MsgThreshold is reached, ithe client would refill the internal buffer by fetching more messages from the consumer (again, up to MaxMsgs). All in all the, messages in the internal buffer would amount to at most MaxMsgs ack pendings.
But what we are observing defies our expectations (or maybe our mental model concerning ConsumeAsync is just not correct :sweat_smile:) : we are always fetching up to 1000 messages (the default) not matter what value MaxMsgs is set to.
(how to reproduce it in the thread. Tested on client 2.2.1 (edited)

**Comment by mtmk** [comment]
> > thanks. so, it looks like we are pulling until the internal channel is full which is set to a hard coded value of 1000.
> > [@Miguel Pires](https://natsio.slack.com/team/U076F6NFEAF)
> > we have a [fix to limit the channel capacity](https://github.com/nats-io/nats.net.v2/pull/508) which in turn throttles pull requests. we still get a few more because of pre-fetching.
> 
> Thanks, this is concerning though, can you confirm the latest branch is absent of this additional pre-fetching (other than upto max msgs) or if it can be disabled entirely, pre-fetching beyond maxmsgs would be problematic for me and make everything non-determistic, I want to establish a sensible ackwait accepting the performance penalty of max-msg 1, but I wouldn't know how if I have no idea when my ackwait timer starts for each message, it would be need to desired ackwait * max prefetching which would be far too loose. I guess these problems become apparent when processing a message is rather slow (like talking to crappy SaaS like mandrill that can spike to 12seconds to respond) coupled with unprocessed messages (i.e. a storm of emails to be sent), I going to see a lot of redelivery if theres some unknown prefetching too (with say an ackwait for 30s)..
> 
> .Update: If I'm reading this correctly https://github.com/nats-io/nats.net/pull/508/files nothing in there doing any sneaky prefetching beyond max-msgs? that would correlate with 99 unprocessed on test 2 I done... so maybe its all good :)

Yes, pre-fetching should not exceed the max-msgs limit. The idea is to fetch additional messages (up to the max-msgs limit) when the number of consumed messages reaches a threshold, which is set by default to half of max-msgs. This approach ensures a smooth flow of messages without overwhelming the application with too many at once. Our issue was that we were deciding whether to issue a new pull request based on when messages were written to the channel that the application code yielded from. PR #508 addresses this issue by adjusting the calculation to occur after each message is yielded, thereby avoiding erroneous internal buffering.

**Comment by mtmk** [comment]
> So let's say you have MaxMsgs=30, pulls 30 first, then after consuming 15, you would fetch upto another 15 (15x JS.API.CONSUMER.MSG.NEXT presuming messages are available), and the internal buffer would never exceed 30. I would probably still apperciate a way to disable this though if that's possible. I have a particular use case in one worker where the API partner lets us batch requests to save money, so I have an abstraction over ConsumerAsync that basically Task.WhenAny on MoveNexyAsync and a Task.Delay (as we dont want to wait too long before wrapping up the batch). With this I have to manage ackwait timing very carefully. I worry this would throw it off although I havent drawn it all out yet.
> 
> Maybe NoOverlapFetching : boolean ?

We could potentially do that but I wonder if you can get what you need by adjusting the threshold or instead by using `FetchAsync()` instead?
