### ISSUE TITLE
NatsWebSocketOpts improvements

### ISSUE THREAD

**Issue by mtmk** [nats-io/nats.net#610]
A couple more ideas, which could be done in a follow-up before releasing:

1. Do we want to nest this option under `NatsWebSocketOpts` instead of setting it directly in `NatsOpts`?  This could make it easier to offer a shortcuts for popular options such as adding headers:

```
public sealed record NatsWebSocketOpts
{
    public Dictionary<string, StringValues>? RequestHeaders { get; init; }

    public Func<Uri, ClientWebSocketOptions, CancellationToken, ValueTask>? ConfigureWebSocketOptions { get; init; }
}
```

2. We probably want to invoke `NatsTlsOpts.AuthenticateAsClientOptionsAsync` and copy both `ClientCertificates` and `RemoteCertificateValidationCallback` to `ClientWebSocketOptions` prior to passing it to the callback

_Originally posted by @caleblloyd in https://github.com/nats-io/nats.net/issues/605#issuecomment-2302900265_

**Comment by Ivandemidov00** [comment]
Hi guys.
I can make these changes. Do I understand correctly that we need to wait first https://github.com/nats-io/nats.net/pull/605 ?

**Comment by mtmk** [comment]
> Hi guys. I can make these changes. Do I understand correctly that we need to wait first #605 ?

thanks @Ivandemidov00 that would be great 👍💯 please tag @caleblloyd in your PR so he can review when he has time ;)
