### ISSUE TITLE
Compiler Error: 'ChannelReader<T>' does not contain a definition for 'ReadAllAsync'

### ISSUE THREAD

**Issue by danyromero-ebet** [nats-io/nats.net#667]
### Observed behavior

When: await foreach (var msg in sub.Msgs.**ReadAllAsync()**) throws a compiler error: ...'ChannelReader<T>' does not contain a definition for 'ReadAllAsync'...

### Expected behavior

await foreach (var msg in sub.Msgs.**ReadAllAsync()**) shouldn't show any error on this line

### Server and client version

I don't think this is relevant however here it is: nats-server: v2.0.0

### Host environment

- Windows 11 Business
- Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.11.0

### Steps to reproduce

- Create a .NET Standard 2.0 class library project
- Then add package: NATS.Net 2.5.2
- And just try to work with this sample code:

```csharp
            await using var nc = new NatsConnection();

            // Connections are lazy, so we need to connect explicitly
            // to avoid any races between subscription and publishing.
            await nc.ConnectAsync();

            await using var sub = await nc.SubscribeCoreAsync<int>("foo");

            for (var i = 0; i < 10; i++)
            {
                Console.WriteLine($" Publishing {i}...");
                await nc.PublishAsync<int>("foo", i);
            }

            // Signal subscription to stop
            await nc.PublishAsync<int>("foo", -1);

            // Messages have been collected in the subscription internal channel
            // now we can drain them
            await foreach (var msg in sub.Msgs.ReadAllAsync())
            {
                Console.WriteLine($"Received {msg.Subject}: {msg.Data}\n");
                if (msg.Data == -1)
                    break;
            }

            // We can unsubscribe from the subscription explicitly
            // (otherwise dispose will do it for us)
            await sub.UnsubscribeAsync();
```

**Comment by mtmk** [comment]
that's not available in netstandard. we have an extension but currently it's internal

https://github.com/nats-io/nats.net/blob/06156f9831271e92e22784c184a292e8f8c0a1c0/src/NATS.Client.Core/Internal/netstandard.cs#L329-L331

**Comment by danyromero-ebet** [comment]
> that's not available in netstandard. we have an extension but currently it's internal
> 
> https://github.com/nats-io/nats.net/blob/06156f9831271e92e22784c184a292e8f8c0a1c0/src/NATS.Client.Core/Internal/netstandard.cs#L329-L331

Thanks @mtmk

**Comment by to11mtm** [comment]
FWIW, This should be handled better for everyone in the 9.0 release of System.Threading.Channels package per https://github.com/dotnet/runtime/pull/94417 . 

That change adds `ReadAllAsync` to NetStandard, have confirmed this via checking prerelease, `<PackageReference Include="System.Threading.Channels" Version="9.0.0-rc.2.24473.5" />`. I expect that per .NET cadence, the non-prerelase 9.0 version will be released by EOY.

In the meantime as a workaround, you may want to consider either trying the prerelease versions, or following the `internal` extension pattern exampled by @mtmk in the meantime.
