### ISSUE TITLE
`CreateOrUpdateStreamAsync`?

### ISSUE THREAD

**Issue by aradalvand** [nats-io/nats.net#676]
### Proposed change

Add a `CreateOrUpdateStreamAsync` on `INatsJSContext` — analogous to `CreateOrUpdateConsumerAsync` on `INatsJSStream` — the [Go client added this a long time ago](https://github.com/nats-io/nats.go/pull/1395).

### Use case

Obvious; similar to `CreateOrUpdateConsumer`.

**Comment by mtmk** [comment]
if Go has it we can too ;)

I'm guessing it's fine but not sure if there is a race the create would fail if the stream is already there.

**Comment by Ivandemidov00** [comment]
Hi guys!
Can I do this task?

**Comment by mtmk** [comment]
> Hi guys! Can I do this task?

thanks @Ivandemidov00 assigned it to you please feel free to open a PR
