### ISSUE TITLE
Add .NET 9 framework support

### ISSUE THREAD

**Issue by darkwatchuk** [nats-io/nats.net#681]
### Proposed change

Is it possible to have .NET 9 supported as a compile target for the projects?

### Use case

Better native support for .NET 9 applications

**Comment by darkwatchuk** [comment]
:-) It's not a biggie, was more inherit some benefit for free from the latest runtime, and I guess a starting point for anything more long term for 10 LTS.  Was just watching Stephen Toub's video on .Net 9 performance, and have started on the longer blog post, some nice new features which maybe useful in future....

**Comment by mtmk** [comment]
apart from [this](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/libraries#params-readonlyspant-overloads) (which I haven't verified if it makes any difference if at all) I think vast majority are JIT and runtime related. so as long as the applications target 9 referenced library targets does not seem to have much effect as long as they use 8 features.
