### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by matteoventuri7** [nats-io/nats.net#682]
### Observed behavior

The example reported from Quick Start section inhttps://github.com/nats-io/nats.net is not working.
Error: NATS.Client.Core.NatsException: 'can not connect uris: nats://localhost:4222'

### Expected behavior

The example works.

### Server and client version

NATS.Net 2.5.4
.Net 8

### Host environment

Visual Studio 2022 17.11.6
Windows 11

### Steps to reproduce

Create a .Net 8 Console App.
Execute the command dotnet add package NATS.Net
Copy this code:
```
// NATS core M:N messaging example
using NATS.Net;

await using var nc = new NatsClient();

// Subscribe on one terminal
await foreach (var msg in nc.SubscribeAsync<string>(subject: "foo"))
{
    Console.WriteLine($"Received: {msg.Data}");
}

// Start publishing to the same subject on a second terminal
await nc.PublishAsync(subject: "foo", data: "Hello, World!");
```

Run

**Comment by mtmk** [comment]
you need to run a NATS Server locally or use the demo server `demo.nats.io` is you are not behind a firewall.
```csharp
await using var nc = new NatsClient("demo.nats.io");
```

Also not in the example above you need to create two console apps one for publishing and one for subscribing or place the subscription in a task and don't exist the program.

Here is another example:
```csharp
// dotnet add package NATS.Net
using NATS.Net;

await using var nc = new NatsClient("demo.nats.io");

var subscription = Task.Run(async () =>
{
    await foreach (var msg in nc.SubscribeAsync<string>(subject: "foo"))
    {
        Console.WriteLine($"Received: {msg.Data}");
        if (msg.Data == "exit")
        {
            break;
        }
    }
});

for (var i = 0; i < 10; i++)
{
    await Task.Delay(1000);
    Console.WriteLine("Publishing message...");
    await nc.PublishAsync(subject: "foo", data: $"{DateTime.Now} Hello, World!");
}

await nc.PublishAsync(subject: "foo", data: $"exit");

await subscription;
```

**Comment by mtmk** [comment]
btw thanks for the heads up @matteoventuri7 we'll add a bit to readme about the server.
